//go:build integration

// engine/imaging/scan_integration_test.go — the scanner over the COMMITTED
// binary fixtures.
//
// TIER: integration (docs/TESTING.md). It reads real files from
// backend/testdata/ and walks them with the standard library's zip reader, which
// is real-format behaviour rather than logic: the unit tier next door already
// owns every rule, over archives it builds in memory. This is the one end-to-end
// happy path per input format the tier discipline asks for, and what it adds is
// that the fixtures on disk still say what the rules expect.
//
// The fixtures are generated by engine/convert/fixtures_test.go. If one is
// missing, run `go test -tags=integration ./backend/engine/convert/` once and
// commit what it writes.
package imaging_test

import (
	"encoding/base64"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"doc-anonymiser/backend/engine/imaging"
)

// committedFixture reads one file out of backend/testdata/.
func committedFixture(t *testing.T, name string) []byte {
	t.Helper()
	path := filepath.Join("..", "..", "testdata", name)
	raw, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("could not read the fixture %s: %v; generate it with "+
			"`go test -tags=integration ./backend/engine/convert/` and commit it", path, err)
	}
	return raw
}

// TestScanCommittedPptx: the deck fixture holds four pictures, one of them used
// twice, one on the master, one vector, one on a hidden slide.
func TestScanCommittedPptx(t *testing.T) {
	t.Run("extraction/scan_committed_pptx", func(t *testing.T) {
		inv, err := imaging.ScanPptx(committedFixture(t, "images.pptx"))
		if err != nil {
			t.Fatalf("ScanPptx(images.pptx): %v, want no error", err)
		}
		if !inv.Applicable {
			t.Fatal("a .pptx must always be applicable for image review")
		}
		if len(inv.Assets) != 4 {
			t.Fatalf("got %d assets, want 4", len(inv.Assets))
		}

		want := map[string]struct {
			occurrences int
			format      imaging.Format
			location    string
		}{
			"ppt/media/image1.png":  {2, imaging.FormatPNG, "Slide 1"},
			"ppt/media/image2.png":  {1, imaging.FormatSVG, "Slide 1"},
			"ppt/media/image5.png":  {1, imaging.FormatPNG, "Hidden slide 4"},
			"ppt/media/image4.jpeg": {1, imaging.FormatJPEG, "Slide master"},
		}
		for _, asset := range inv.Assets {
			expect, known := want[asset.ID]
			if !known {
				t.Errorf("unexpected asset %q in the fixture", asset.ID)
				continue
			}
			if len(asset.Occurrences) != expect.occurrences {
				t.Errorf("%s has %d occurrences, want %d", asset.ID, len(asset.Occurrences), expect.occurrences)
			}
			if asset.Format != expect.format {
				t.Errorf("%s has format %q, want %q", asset.ID, asset.Format, expect.format)
			}
			if got := asset.Occurrences[0].Location; got != expect.location {
				t.Errorf("%s is first located %q, want %q", asset.ID, got, expect.location)
			}
		}
	})
}

// TestScanCommittedDocx: the document fixture holds the four picture shapes Word
// writes, plus one in a header, and the page rule applies to the body ones.
func TestScanCommittedDocx(t *testing.T) {
	t.Run("extraction/scan_committed_docx", func(t *testing.T) {
		inv, err := imaging.ScanDocx(committedFixture(t, "images.docx"))
		if err != nil {
			t.Fatalf("ScanDocx(images.docx): %v, want no error", err)
		}
		if len(inv.Assets) != 5 {
			t.Fatalf("got %d assets, want 5", len(inv.Assets))
		}
		want := []string{"Page 1", "Page 1", "Page 1", "Page 2", "Header"}
		for i, asset := range inv.Assets {
			if got := asset.Occurrences[0].Location; got != want[i] {
				t.Errorf("asset %d (%s) is located %q, want %q", i, asset.ID, got, want[i])
			}
		}
	})
}

// TestPreviewCommittedFixtures: what the review screen puts in an <img src>.
// A raster asset arrives as a PNG data URL and a vector one as its own SVG,
// because an SVG is what the user sees and rasterising it is not something the
// standard library can do.
func TestPreviewCommittedFixtures(t *testing.T) {
	raw := committedFixture(t, "images.pptx")
	inv, err := imaging.ScanPptx(raw)
	if err != nil {
		t.Fatalf("ScanPptx(images.pptx): %v", err)
	}

	for _, asset := range inv.Assets {
		asset := asset
		t.Run("extraction/preview_"+string(asset.Format), func(t *testing.T) {
			url, w, h, err := imaging.Preview(raw, asset, 64)
			if err != nil {
				t.Fatalf("Preview(%s): %v, want no error", asset.ID, err)
			}
			wantPrefix := "data:image/png;base64,"
			if asset.Format == imaging.FormatSVG {
				wantPrefix = "data:image/svg+xml;base64,"
			}
			if !strings.HasPrefix(url, wantPrefix) {
				t.Fatalf("the preview of %s starts %.40q, want the prefix %q", asset.ID, url, wantPrefix)
			}
			payload, err := base64.StdEncoding.DecodeString(strings.TrimPrefix(url, wantPrefix))
			if err != nil {
				t.Fatalf("the preview of %s is not decodable base64: %v", asset.ID, err)
			}
			if len(payload) == 0 {
				t.Fatalf("the preview of %s is empty", asset.ID)
			}
			if w <= 0 || h <= 0 {
				t.Errorf("the preview of %s reports %dx%d, want a real size so the layout can "+
					"reserve the space", asset.ID, w, h)
			}
			if asset.Format != imaging.FormatSVG && (w > 64 || h > 64) {
				t.Errorf("the preview of %s is %dx%d, want nothing above the 64 pixel limit asked for",
					asset.ID, w, h)
			}
		})
	}
}
