// engine/loadall_test.go — tests for the multi-format ingestion dispatch
// (BUILD.md Phase 1B activity 5): one imported file may yield multiple
// Documents (xlsx sheets), conversion warnings surface on the Document, and
// unsupported extensions stay rejected.
package engine

import (
	"os"
	"strings"
	"testing"
)

// loadFixture reads a committed testdata file (generated by the convert
// package's fixture helpers and committed to the repository).
func loadFixture(t *testing.T, name string) []byte {
	t.Helper()
	raw, err := os.ReadFile("../testdata/" + name)
	if err != nil {
		t.Fatalf("fixture %s missing — run 'go test ./engine/convert/' once to generate it: %v", name, err)
	}
	return raw
}

func TestLoadAllDocx(t *testing.T) {
	docs, err := LoadAll("report.docx", loadFixture(t, "report.docx"))
	if err != nil {
		t.Fatalf("LoadAll: %v", err)
	}
	if len(docs) != 1 || docs[0].Format != FormatDOCX {
		t.Fatalf("want one docx Document, got %d (%v)", len(docs), docs[0].Format)
	}
	if !strings.Contains(docs[0].Markdown, "# Engagement Report") {
		t.Error("docx heading missing from working form")
	}
	// The dropped-image conversion warning must reach the Document.
	if len(docs[0].Warnings) == 0 || !strings.Contains(strings.Join(docs[0].Warnings, " "), "image") {
		t.Errorf("conversion warning lost: %v", docs[0].Warnings)
	}
}

func TestLoadAllXlsxYieldsOneDocumentPerSheet(t *testing.T) {
	docs, err := LoadAll("workbook.xlsx", loadFixture(t, "workbook.xlsx"))
	if err != nil {
		t.Fatalf("LoadAll: %v", err)
	}
	if len(docs) != 2 {
		t.Fatalf("want 2 Documents (one per sheet), got %d", len(docs))
	}

	flat := docs[0]
	// Naming convention from CLAUDE.md §5: <workbook>.xlsx#<sheet>.
	if flat.Name != "workbook.xlsx#Clients" {
		t.Errorf("flat sheet name = %q, want workbook.xlsx#Clients", flat.Name)
	}
	if flat.Format != FormatXLSX || flat.Grid == nil {
		t.Errorf("flat sheet must behave like CSV (FormatXLSX + Grid), got %v grid=%v", flat.Format, flat.Grid != nil)
	}
	// Flat sheets must round-trip to CSV exactly like a CSV import.
	if _, err := GridToCSV(flat.Grid); err != nil {
		t.Errorf("flat sheet CSV round-trip failed: %v", err)
	}
	if !strings.Contains(flat.Markdown, "| name | client | email |") {
		t.Errorf("flat sheet markdown table missing header:\n%s", flat.Markdown)
	}

	complexDoc := docs[1]
	if complexDoc.Name != "workbook.xlsx#Résumé" || complexDoc.Format != FormatXLSXJSON {
		t.Errorf("complex sheet = %q/%v, want workbook.xlsx#Résumé / xlsx-json", complexDoc.Name, complexDoc.Format)
	}
	// COMPLEX sheets render as a fenced JSON block and keep the raw JSON
	// for the .json export path.
	if !strings.HasPrefix(complexDoc.Markdown, "```json\n") || complexDoc.JSON == "" {
		t.Errorf("complex sheet must carry fenced-JSON markdown and raw JSON")
	}
	if len(complexDoc.Warnings) == 0 || !strings.Contains(complexDoc.Warnings[0], "complex layout") {
		t.Errorf("complex routing warning missing: %v", complexDoc.Warnings)
	}
}

func TestLoadAllPdf(t *testing.T) {
	t.Run("text layer converts with repair", func(t *testing.T) {
		docs, err := LoadAll("textlayer.pdf", loadFixture(t, "textlayer.pdf"))
		if err != nil {
			t.Fatalf("LoadAll: %v", err)
		}
		if len(docs) != 1 || docs[0].Format != FormatPDF {
			t.Fatalf("want one pdf Document, got %d", len(docs))
		}
		if !strings.Contains(docs[0].Markdown, "BIDDING RULES") {
			t.Error("spacing repair missing in working form")
		}
		if !strings.Contains(strings.Join(docs[0].Warnings, " "), "EXPERIMENTAL") {
			t.Errorf("experimental warning missing: %v", docs[0].Warnings)
		}
	})
	t.Run("scanned pdf rejected with the pinned message", func(t *testing.T) {
		_, err := LoadAll("scanned.pdf", loadFixture(t, "scanned.pdf"))
		if err == nil || !strings.Contains(err.Error(), "No text layer found") {
			t.Errorf("want the scanned-PDF rejection, got %v", err)
		}
	})
}

func TestLoadAllTextFormatsAndRejection(t *testing.T) {
	// Text formats flow through the Phase-1 Load path unchanged.
	docs, err := LoadAll("notes.txt", []byte("hello\r\nworld"))
	if err != nil || len(docs) != 1 || docs[0].Markdown != "hello\nworld" {
		t.Errorf("txt through LoadAll broken: %v %v", docs, err)
	}
	// Unsupported extensions are rejected on drop as well as in the
	// dialog filter (CLAUDE.md §5).
	if _, err := LoadAll("archive.zip", []byte("x")); err == nil || !strings.Contains(err.Error(), ".docx") {
		t.Errorf("unsupported extension must be rejected with the supported list, got %v", err)
	}
}
