// engine/exportfmt/exportfmt_test.go — the UNIT-tier exportfmt tests and the
// shared test helpers for every tier.
//
// TIER: unit (docs/TESTING.md). Two kinds of thing live here:
//
//  1. The SHARED HELPERS. This file carries NO build tag, so its helpers
//     (fixture, testConfig, zip/PDF readers, the bespoke-fixture builders)
//     are compiled into every tier and the integration files can call them.
//     A helper unused by the unit tests is still legal Go; it exists for the
//     integration tests next door.
//  2. The UNIT tests themselves: the ones that need no committed fixture and
//     assert a business rule rather than real-format behaviour. The filename
//     mapping is pure string work; the two ExportPDF guards (empty-text
//     rejection, leak self-check) are logic the integration tier must not
//     re-verify.
//
// The format round-trips that decode or rewrite real .docx/.pptx/.xlsx/.pdf
// bytes are in exportfmt_integration_test.go, metadata_integration_test.go and
// pdf_integration_test.go.
package exportfmt

import (
	"archive/zip"
	"bytes"
	"crypto/sha256"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"testing"
	"time"

	ledongthuc "github.com/ledongthuc/pdf"

	"doc-anonymiser/backend/engine"
)

// --- shared helpers (untagged: visible to every tier) --------------------

// fixture loads a committed testdata file (generated by the convert
// package's fixture helper; run `go test ./engine/convert/` once if a
// file is missing).
func fixture(t *testing.T, name string) []byte {
	t.Helper()
	data, err := os.ReadFile(filepath.Join("..", "..", "testdata", name))
	if err != nil {
		t.Fatalf("fixture %s missing, run 'go test ./engine/convert/' once to generate it: %v", name, err)
	}
	return data
}

// pdfFixture loads a committed PDF fixture.
func pdfFixture(t *testing.T, name string) []byte {
	t.Helper()
	data, err := os.ReadFile(filepath.Join("..", "..", "testdata", name))
	if err != nil {
		t.Fatalf("fixture %s missing, run 'go test ./engine/convert/' once to generate it: %v", name, err)
	}
	return data
}

// testConfig builds a Config with a fresh registry and the given entities
// at medium level.
func testConfig(entities ...engine.Value) Config {
	return Config{
		Values:    entities,
		Level:     engine.LevelMedium,
		Allowlist: engine.NewEmptyAllowlist(),
		Registry:  engine.NewRegistry(),
	}
}

// zipEntryHashes maps entry name → content hash for passthrough checks.
func zipEntryHashes(t *testing.T, raw []byte) map[string]string {
	t.Helper()
	r, err := zip.NewReader(bytes.NewReader(raw), int64(len(raw)))
	if err != nil {
		t.Fatal(err)
	}
	out := map[string]string{}
	for _, f := range r.File {
		src, err := f.Open()
		if err != nil {
			t.Fatal(err)
		}
		content, err := io.ReadAll(src)
		src.Close()
		if err != nil {
			t.Fatal(err)
		}
		out[f.Name] = fmt.Sprintf("%x", sha256.Sum256(content))
	}
	return out
}

// buildZip assembles a small deterministic OOXML zip for bespoke fixtures.
func buildZip(t *testing.T, entries map[string]string) []byte {
	t.Helper()
	var names []string
	for n := range entries {
		names = append(names, n)
	}
	sort.Strings(names)
	var buf bytes.Buffer
	w := zip.NewWriter(&buf)
	for _, n := range names {
		fh := &zip.FileHeader{Name: n, Method: zip.Deflate}
		fh.Modified = time.Date(2026, 1, 1, 0, 0, 0, 0, time.UTC)
		fw, err := w.CreateHeader(fh)
		if err != nil {
			t.Fatal(err)
		}
		if _, err := fw.Write([]byte(entries[n])); err != nil {
			t.Fatal(err)
		}
	}
	if err := w.Close(); err != nil {
		t.Fatal(err)
	}
	return buf.Bytes()
}

// buildPropsDocx assembles a minimal docx with authored core, app and
// custom properties (the props.docx equivalent from the plan, built by a
// test helper).
func buildPropsDocx(t *testing.T) []byte {
	t.Helper()
	return buildZip(t, map[string]string{
		"[Content_Types].xml": `<?xml version="1.0"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/></Types>`,
		"_rels/.rels":         `<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/></Relationships>`,
		"word/document.xml":   `<?xml version="1.0"?><w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body><w:p><w:r><w:t>Body about Alpine Trust.</w:t></w:r></w:p></w:body></w:document>`,
		"docProps/core.xml": `<?xml version="1.0"?><cp:coreProperties xmlns:cp="http://schemas.openxmlformats.org/package/2006/metadata/core-properties" xmlns:dc="http://purl.org/dc/elements/1.1/">` +
			`<dc:title>Alpine Trust engagement report</dc:title>` +
			`<dc:subject>CSSF filing</dc:subject>` +
			`<dc:creator>Marie Duval</dc:creator>` +
			`<cp:lastModifiedBy>Marie Duval</cp:lastModifiedBy>` +
			`<cp:keywords>alpine; audit</cp:keywords>` +
			`<dc:description>Prepared for Alpine Trust &amp; partners</dc:description>` +
			`</cp:coreProperties>`,
		"docProps/app.xml": `<?xml version="1.0"?><Properties xmlns="http://schemas.openxmlformats.org/officeDocument/2006/extended-properties">` +
			`<Company>Alpine Trust S.A.</Company><Manager>Marie Duval</Manager><Pages>3</Pages></Properties>`,
		"docProps/custom.xml": `<?xml version="1.0"?><Properties xmlns="http://schemas.openxmlformats.org/officeDocument/2006/custom-properties" xmlns:vt="http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes">` +
			`<property fmtid="{D5CDD505-2E9C-101B-9397-08002B2CF9AE}" pid="2" name="Client"><vt:lpwstr>Alpine Trust</vt:lpwstr></property>` +
			`<property fmtid="{D5CDD505-2E9C-101B-9397-08002B2CF9AE}" pid="3" name="Reviewed"><vt:bool>true</vt:bool></property>` +
			`</Properties>`,
	})
}

// extractEntry reads one entry of a zip archive as a string.
func extractEntry(t *testing.T, raw []byte, name string) string {
	t.Helper()
	r, err := zip.NewReader(bytes.NewReader(raw), int64(len(raw)))
	if err != nil {
		t.Fatal(err)
	}
	for _, f := range r.File {
		if f.Name == name {
			src, err := f.Open()
			if err != nil {
				t.Fatal(err)
			}
			defer src.Close()
			content, err := io.ReadAll(src)
			if err != nil {
				t.Fatal(err)
			}
			return string(content)
		}
	}
	t.Fatalf("entry %q missing", name)
	return ""
}

// extractAllPDFText reads every page of a PDF with the import reader.
func extractAllPDFText(t *testing.T, raw []byte) string {
	t.Helper()
	reader, err := ledongthuc.NewReader(bytes.NewReader(raw), int64(len(raw)))
	if err != nil {
		t.Fatalf("generated PDF unreadable: %v", err)
	}
	var b strings.Builder
	for i := 1; i <= reader.NumPage(); i++ {
		page := reader.Page(i)
		if page.V.IsNull() {
			continue
		}
		if text, err := page.GetPlainText(nil); err == nil {
			b.WriteString(text)
			b.WriteString("\n")
		}
	}
	return b.String()
}

// --- unit tests ----------------------------------------------------------

// TestSameFormatFileName is pure string mapping over registry entries: no
// fixture, no format decoding, so it is a unit test.
func TestSameFormatFileName(t *testing.T) {
	reg := engine.NewRegistry()
	reg.Assign("entity_names", "Alpine Trust")
	reg.Assign("person_names", "Amélie Lefèvre")
	entries := reg.Entries()

	cases := []struct {
		name, docName, ext, want string
	}{
		{"client term replaced", "Alpine Trust report.docx", "docx", "ENTITY_1 report_anon.docx"},
		{"entirely one entity falls back", "Alpine Trust.docx", "docx", "ENTITY_1_anon.docx"},
		{"unicode name replaced", "notes Amélie Lefèvre.pptx", "pptx", "notes PERSON_1_anon.pptx"},
		{"sheet hash sanitised", "workbook.xlsx#Clients", "xlsx", "workbook.xlsx_Clients_anon.xlsx"},
		{"glued original falls back", "AlpineTrustAlpine Trust.docx", "docx", "document_anon_7.docx"},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			got := engine.SameFormatFileName(tc.docName, tc.ext, entries, 7)
			if got != tc.want {
				t.Errorf("SameFormatFileName(%q) = %q, want %q", tc.docName, got, tc.want)
			}
		})
	}
}

// TestExportPDFRejectsEmptyText: a scanned PDF never yields working text; the
// export refuses with the pinned scanned-PDF message. Pure guard, no fixture.
func TestExportPDFRejectsEmptyText(t *testing.T) {
	_, err := ExportPDF("   ", nil, testConfig())
	if err == nil || !strings.Contains(err.Error(), "No text layer found") {
		t.Errorf("empty text must be rejected with the scanned-PDF message, got %v", err)
	}
}

// TestExportPDFSelfCheckBlocksLeaks: inject a mapping the generator "ignores",
// so the anonymised text still contains a registry original; the self-check
// must FAIL the export and return no bytes. This is the leak-guard business
// rule, so it belongs to the unit tier, not integration.
func TestExportPDFSelfCheckBlocksLeaks(t *testing.T) {
	cfg := testConfig()
	cfg.Registry.Assign("entity_names", "Zephyr Capital")
	out, err := ExportPDF("This text still mentions Zephyr Capital openly.", nil, cfg)
	if err == nil || out != nil {
		t.Fatalf("leaky export must fail, got bytes=%v err=%v", out != nil, err)
	}
	if !strings.Contains(err.Error(), "self-check failed") {
		t.Errorf("error must name the self-check: %v", err)
	}
	if strings.Contains(err.Error(), "Zephyr Capital") {
		t.Errorf("the full original must not be repeated in the error: %v", err)
	}
}
