//go:build integration

// engine/exportfmt/images_integration_test.go — the picture pass over the
// COMMITTED fixtures.
//
// TIER: integration (docs/TESTING.md). It rewrites real archives read from
// backend/testdata/ and re-opens what it produced, which is real-format behaviour
// rather than logic: the unit tier next door owns the pass's rules over archives
// it builds in memory, and engine/imaging owns the treatments themselves. What
// this adds is that a produced .docx and .pptx still open, still parse, and no
// longer carry the pictures the user redacted.
//
// TestExportedArchiveKeepsNoOriginalBytes IS LOAD-BEARING. It is the permanent
// guard for the first invariant of this feature: the original pixels always leave
// the archive. Do not narrow it into a spot check on one entry, and do not
// weaken it to "the media folder changed": a removal that deleted the drawing
// element and left the picture part behind would pass that and would be a leak
// that LOOKS like a redaction, which is worse than no feature.
//
// The fixtures are generated by engine/convert/fixtures_test.go. If one is
// missing, run `go test -tags=integration ./backend/engine/convert/` once and
// commit what it writes.
package exportfmt

import (
	"archive/zip"
	"bytes"
	"crypto/sha256"
	"encoding/xml"
	"errors"
	_ "image/jpeg"
	_ "image/png"
	"io"
	"strings"
	"testing"

	"doc-anonymiser/backend/engine/imaging"
)

// treatedFixture is one committed fixture with a decision of each kind applied.
type treatedFixture struct {
	name string
	// file is the fixture in backend/testdata/.
	file string
	// scan reads the fixture's inventory the way the bound layer does.
	scan func([]byte) (imaging.Inventory, error)
	// export produces the anonymised copy.
	export func([]byte, Config) ([]byte, imaging.Summary, error)
	// decisions is asset ID -> decision, covering every treatment.
	decisions map[string]imaging.Decision
	// wantSummary is what the export must report it did, per ASSET.
	wantSummary imaging.Summary
	// wantSize is the pixel size each treated PART must come back at: a box and
	// a blur keep the source's size, and a removal is the one-pixel blank. It is
	// keyed by part rather than by asset because an SVG picture is TWO parts and
	// both of them are treated.
	wantSize map[string][2]int
	// wantFormat is the encoding each treated part must come back in.
	wantFormat map[string]imaging.Format
	// gonePart names the part a removed picture's element must have left, and
	// goneName is how that element identifies itself in the part's own words.
	gonePart, goneName string
	// staysPart is the part the SPLICE ORDER is held over, and staysNames are the
	// picture elements that must survive in it. A deletion is a byte-range edit,
	// and one applied in the wrong order damages the element next to it: the
	// interesting case is a removal beside a picture nobody decided anything
	// about, which is exactly what the docx fixture holds.
	staysPart  string
	staysNames []string
}

func fixtures() []treatedFixture {
	return []treatedFixture{
		{
			name: "roundtrip/export_images_pptx",
			file: "images.pptx",
			scan: imaging.ScanPptx,
			export: func(raw []byte, cfg Config) ([]byte, imaging.Summary, error) {
				out, _, summary, err := ExportPptx(raw, cfg)
				return out, summary, err
			},
			decisions: map[string]imaging.Decision{
				"ppt/media/image1.png": {Treatment: imaging.TreatmentBox, BoxText: "Client logo removed"},
				// The SVG picture: one asset whose bytes live in TWO parts, the
				// PNG fallback the relationship points at and the SVG in the
				// blip's extension. Treating one and not the other means a
				// "boxed" logo comes back sharp on whichever machine renders the
				// part that was left alone.
				"ppt/media/image2.png":  {Treatment: imaging.TreatmentBox, BoxText: "Schéma retiré"},
				"ppt/media/image4.jpeg": {Treatment: imaging.TreatmentBlur, BlurStrength: 8},
				"ppt/media/image5.png":  {Treatment: imaging.TreatmentRemove},
			},
			wantSummary: imaging.Summary{Boxed: 2, Blurred: 1, Removed: 1},
			wantSize: map[string][2]int{
				"ppt/media/image1.png":  {120, 80},
				"ppt/media/image2.png":  {300, 150},
				"ppt/media/image3.svg":  {300, 150},
				"ppt/media/image4.jpeg": {200, 200},
				"ppt/media/image5.png":  {1, 1},
			},
			wantFormat: map[string]imaging.Format{
				"ppt/media/image1.png": imaging.FormatPNG,
				"ppt/media/image2.png": imaging.FormatPNG,
				// The companion comes back as an SVG, because a replacement is
				// written in the SOURCE part's own encoding: the archive's
				// content types map an extension to a media type, and PNG bytes
				// under a .svg name are a part Office may refuse to draw.
				"ppt/media/image3.svg":  imaging.FormatSVG,
				"ppt/media/image4.jpeg": imaging.FormatJPEG,
				"ppt/media/image5.png":  imaging.FormatPNG,
			},
			gonePart: "ppt/slides/slide4.xml", goneName: "Photo équipe",
			// Both of slide 1's pictures are boxed, and a box must never delete
			// an element: it replaces the bytes the element draws.
			staysPart:  "ppt/slides/slide1.xml",
			staysNames: []string{"Alpine Trust logo", "Schéma Borealis"},
		},
		{
			name: "roundtrip/export_images_docx",
			file: "images.docx",
			scan: imaging.ScanDocx,
			export: func(raw []byte, cfg Config) ([]byte, imaging.Summary, error) {
				out, _, _, summary, err := ExportDocx(raw, cfg)
				return out, summary, err
			},
			decisions: map[string]imaging.Decision{
				"word/media/image1.png":  {Treatment: imaging.TreatmentBox, BoxText: "Logo"},
				"word/media/image2.jpeg": {Treatment: imaging.TreatmentBlur, BlurStrength: 5},
				// The legacy VML picture, whose removable element is a w:pict
				// rather than a w:drawing.
				"word/media/image3.png": {Treatment: imaging.TreatmentRemove},
			},
			wantSummary: imaging.Summary{Kept: 2, Boxed: 1, Blurred: 1, Removed: 1},
			wantSize: map[string][2]int{
				"word/media/image1.png":  {120, 80},
				"word/media/image2.jpeg": {200, 200},
				"word/media/image3.png":  {1, 1},
			},
			wantFormat: map[string]imaging.Format{
				"word/media/image1.png":  imaging.FormatPNG,
				"word/media/image2.jpeg": imaging.FormatJPEG,
				"word/media/image3.png":  imaging.FormatPNG,
			},
			gonePart: "word/document.xml", goneName: "v:imagedata",
			// The remove-beside-a-keep case over a real archive: the legacy VML
			// picture is deleted out of the middle of word/document.xml, and the
			// picture AFTER it is one nobody decided anything about. A splice
			// applied in the wrong order eats into its element.
			staysPart:  "word/document.xml",
			staysNames: []string{"Organigramme", "Alpine Trust logo"},
		},
	}
}

// entriesOf reads a whole archive into name -> content.
func entriesOf(t *testing.T, raw []byte) map[string][]byte {
	t.Helper()
	zr, err := zip.NewReader(bytes.NewReader(raw), int64(len(raw)))
	if err != nil {
		t.Fatalf("the produced file is not a zip archive: %v", err)
	}
	out := map[string][]byte{}
	for _, f := range zr.File {
		rc, err := f.Open()
		if err != nil {
			t.Fatalf("could not open %q: %v", f.Name, err)
		}
		data, err := io.ReadAll(rc)
		rc.Close()
		if err != nil {
			t.Fatalf("could not read %q: %v", f.Name, err)
		}
		out[f.Name] = data
	}
	return out
}

// wellFormed parses every XML part, which is what a byte-range deletion can
// break.
func wellFormed(t *testing.T, entries map[string][]byte) {
	t.Helper()
	for name, data := range entries {
		if !strings.HasSuffix(name, ".xml") && !strings.HasSuffix(name, ".rels") {
			continue
		}
		dec := xml.NewDecoder(bytes.NewReader(data))
		for {
			_, err := dec.Token()
			if errors.Is(err, io.EOF) {
				break
			}
			if err != nil {
				t.Fatalf("the part %q no longer parses as XML after the picture pass: %v", name, err)
			}
		}
	}
}

// TestExportImagesOverTheCommittedFixtures: one decision of each kind against a
// real archive, then re-open what came out.
func TestExportImagesOverTheCommittedFixtures(t *testing.T) {
	for _, f := range fixtures() {
		t.Run(f.name, func(t *testing.T) {
			raw := fixture(t, f.file)
			inv, err := f.scan(raw)
			if err != nil {
				t.Fatalf("the fixture does not scan: %v", err)
			}
			cfg := testConfig()
			cfg.Images = ImagePlan{Inventory: inv, Decisions: f.decisions}

			out, summary, err := f.export(raw, cfg)
			if err != nil {
				t.Fatalf("the export failed: %v", err)
			}
			if summary != f.wantSummary {
				t.Errorf("the summary is %+v, want %+v: it is what the report and the export "+
					"screen both state, so it has to describe what the pass actually did",
					summary, f.wantSummary)
			}
			if summary.Total() != len(inv.Assets) {
				t.Errorf("the summary counts %d pictures, the document has %d",
					summary.Total(), len(inv.Assets))
			}

			entries := entriesOf(t, out)
			wellFormed(t, entries)

			for id, want := range f.wantSize {
				data, ok := entries[id]
				if !ok {
					t.Errorf("the treated picture %q is missing from the produced archive; its "+
						"bytes must be replaced, not dropped, or the relationship points at "+
						"nothing", id)
					continue
				}
				format := imaging.Sniff(data)
				if format != f.wantFormat[id] {
					t.Errorf("%q came back as %s, want %s: the archive's content types are "+
						"declared by extension", id, format, f.wantFormat[id])
				}
				// Through Measure rather than image.DecodeConfig, because an SVG
				// companion is one of the parts under test and only Measure can
				// read a vector's size.
				w, h, ok := imaging.Measure(data, format)
				if !ok {
					t.Errorf("the treated picture %q states no size, so nothing can confirm the "+
						"replacement fills the frame the original did", id)
					continue
				}
				if w != want[0] || h != want[1] {
					t.Errorf("%q is %dx%d, want %dx%d", id, w, h, want[0], want[1])
				}
			}

			if part, ok := entries[f.gonePart]; ok {
				if strings.Contains(string(part), f.goneName) {
					t.Errorf("the removed picture's element is still in %q; the file still draws "+
						"it", f.gonePart)
				}
			} else {
				t.Errorf("the produced archive lost the part %q entirely", f.gonePart)
			}

			// The splice order: what had to survive the deletion beside it.
			if stays, ok := entries[f.staysPart]; ok {
				for _, name := range f.staysNames {
					if !strings.Contains(string(stays), name) {
						t.Errorf("the picture %q is gone from %q; a byte-range deletion applied in "+
							"the wrong order eats into the element next to it, and the pass must "+
							"apply its edits back to front", name, f.staysPart)
					}
				}
			} else {
				t.Errorf("the produced archive lost the part %q entirely", f.staysPart)
			}

			contentTypesCoverEveryPart(t, entries)
			pictureRelationshipsResolve(t, f, out)

			// Everything the user did NOT decide on is still exactly where it was.
			before := entriesOf(t, raw)
			for _, asset := range inv.Assets {
				if f.decisions[asset.ID].Anonymises() {
					continue
				}
				if !bytes.Equal(entries[asset.ID], before[asset.ID]) {
					t.Errorf("the kept picture %q was rewritten; only what the user decided on "+
						"may change", asset.ID)
				}
			}
		})
	}
}

// contentTypesCoverEveryPart checks that the produced archive still DECLARES
// every part it holds.
//
// [Content_Types].xml is what maps a part to a media type, by an extension
// Default or a part-name Override, and Office refuses a package with an
// undeclared part rather than drawing what it can. A treatment that wrote a
// replacement under a new extension would produce exactly that, and every other
// assertion here would still pass.
func contentTypesCoverEveryPart(t *testing.T, entries map[string][]byte) {
	t.Helper()
	declared, ok := entries["[Content_Types].xml"]
	if !ok {
		t.Fatal("the produced archive has no [Content_Types].xml, so it is not a valid package " +
			"at all")
	}
	types := string(declared)
	for name := range entries {
		if name == "[Content_Types].xml" {
			continue
		}
		if strings.Contains(types, `PartName="/`+name+`"`) {
			continue
		}
		dot := strings.LastIndex(name, ".")
		if dot < 0 {
			t.Errorf("the part %q has no extension and no Override, so nothing declares its type",
				name)
			continue
		}
		if !strings.Contains(types, `Extension="`+name[dot+1:]+`"`) {
			t.Errorf("nothing in [Content_Types].xml declares the part %q (no Override for it and "+
				"no Default for %q); Office refuses a package with an undeclared part rather than "+
				"drawing what it can", name, name[dot+1:])
		}
	}
}

// pictureRelationshipsResolve re-scans the PRODUCED archive and checks that
// every picture it still draws points at bytes that are really there.
//
// It goes through the scanner rather than a second XML walk in this file for the
// reason the pass itself does: the scanner is what resolves a blip's
// relationship, and a second resolver could disagree with it and then pass on an
// archive the application cannot read. An unresolvable blip surfaces as the
// unreadable_part warning, so the absence of that warning IS the assertion.
func pictureRelationshipsResolve(t *testing.T, f treatedFixture, out []byte) {
	t.Helper()
	after, err := f.scan(out)
	if err != nil {
		t.Fatalf("the produced archive no longer scans: %v", err)
	}
	for _, warning := range after.Warnings {
		if warning == imaging.WarnUnreadablePart {
			t.Errorf("a picture in the produced archive points at a relationship or a part that "+
				"is not there (%s); the pass must never leave a blip dangling", warning)
		}
	}
	entries := entriesOf(t, out)
	for _, asset := range after.Assets {
		if asset.Linked {
			continue
		}
		if _, ok := entries[asset.ID]; !ok {
			t.Errorf("the produced archive still draws the picture %q, but holds no such part",
				asset.ID)
		}
		if asset.Companion == "" {
			continue
		}
		if _, ok := entries[asset.Companion]; !ok {
			t.Errorf("the produced archive still draws the picture %q, but holds no companion %q",
				asset.ID, asset.Companion)
		}
	}
}

// TestExportedArchiveKeepsNoOriginalBytes is the leak guard, and it is
// LOAD-BEARING: see the file header. For every asset the user anonymised, NO
// entry of the produced archive carries its original bytes and no entry hashes to
// them.
//
// It checks every entry rather than the media part alone on purpose: a producer
// that copied a picture into a second part, or a thumbnail cached under
// docProps/, would leak the very pixels the user redacted, and the media part
// would still look clean.
func TestExportedArchiveKeepsNoOriginalBytes(t *testing.T) {
	for _, f := range fixtures() {
		t.Run("roundtrip/exported_archive_keeps_no_original_bytes_"+f.file, func(t *testing.T) {
			raw := fixture(t, f.file)
			inv, err := f.scan(raw)
			if err != nil {
				t.Fatalf("the fixture does not scan: %v", err)
			}
			cfg := testConfig()
			cfg.Images = ImagePlan{Inventory: inv, Decisions: f.decisions}
			out, _, err := f.export(raw, cfg)
			if err != nil {
				t.Fatalf("the export failed: %v", err)
			}

			before := entriesOf(t, raw)
			after := entriesOf(t, out)

			checked := 0
			for _, asset := range inv.Assets {
				if !f.decisions[asset.ID].Anonymises() {
					continue
				}
				original, ok := before[asset.ID]
				if !ok || len(original) == 0 {
					t.Fatalf("the fixture has no bytes for %q, so this case proves nothing; "+
						"fix the fixture rather than the assertion", asset.ID)
				}
				checked++
				originalHash := sha256.Sum256(original)
				for name, data := range after {
					if bytes.Contains(data, original) {
						t.Errorf("the entry %q of the produced archive contains the original "+
							"bytes of the anonymised picture %q", name, asset.ID)
					}
					if sha256.Sum256(data) == originalHash {
						t.Errorf("the entry %q of the produced archive hashes to the original "+
							"picture %q", name, asset.ID)
					}
				}
				// The companion of an SVG picture carries the SAME picture, so it
				// is held to the same rule.
				if asset.Companion == "" {
					continue
				}
				companion, ok := before[asset.Companion]
				if !ok || len(companion) == 0 {
					continue
				}
				companionHash := sha256.Sum256(companion)
				for name, data := range after {
					if bytes.Contains(data, companion) || sha256.Sum256(data) == companionHash {
						t.Errorf("the entry %q of the produced archive still carries the "+
							"companion %q of the anonymised picture %q",
							name, asset.Companion, asset.ID)
					}
				}
			}
			if checked != len(f.decisions) {
				t.Fatalf("only %d of the %d decided pictures were checked; the plan names "+
					"assets the scan does not list, so the guard is not covering what it "+
					"claims to", checked, len(f.decisions))
			}
		})
	}
}
